org: benzz
app: ben310
service: Bence6

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1

plugins:
  - serverless-offline

functions:
  api:
    handler: handler.handler
    environment:
      CLASS_NAME: "CE 6"
    events:
      - httpApi:
          path: /
          method: get

resources:
  Resources:
    DelfrinandoEmailSns:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ben-email-topic
        Subscription: 
          - Protocol: "email"
            Endpoint: "bengeepaton@gmail.com"
