org: benzz
app: ben310
service: Bence6

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1

functions:
  api:
    handler: handler.handler
    environment:
      CLASS_NAME: "CE 6"
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-offline