# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: benzz
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: ben310
# "service" is the name of this project. This will also be added to your AWS resource names.
service: Bence6

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1

functions:
  api:
    handler: handler.handler
    environment:
      CLASS_NAME: "CE 6"
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-offline