name: CI

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different
  pull_request:
    branches:
      - main  # Change this to your default branch if it's different

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm install

  run_tests:
    runs-on: ubuntu-latest
    needs: install_dependencies  # This job depends on the install_dependencies job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
      
      deploy_to_aws:
    runs-on: ubuntu-latest
    needs: run_tests  # This job depends on the run_tests job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to AWS
        if: success()  # This step runs only if the previous steps were successful
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1  # Change to your desired AWS region